// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeieWqVV-_H9iu_VkTaGMrq3dtdTDLma4',
    appId: '1:50794013537:web:871b8899b39ff48f2c5b20',
    messagingSenderId: '50794013537',
    projectId: 'excelerate-inquisit',
    authDomain: 'excelerate-inquisit.firebaseapp.com',
    storageBucket: 'excelerate-inquisit.firebasestorage.app',
    measurementId: 'G-BNZTVYY6JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2WDz_dOPh_HpmN_Q2kr4ahFsXWjibXMo',
    appId: '1:50794013537:android:214bc4b07a4f9e4f2c5b20',
    messagingSenderId: '50794013537',
    projectId: 'excelerate-inquisit',
    storageBucket: 'excelerate-inquisit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbYb8IDwgb51haUGRA2m7n7C0dZLXa7MY',
    appId: '1:50794013537:ios:680bc6df0fd864f62c5b20',
    messagingSenderId: '50794013537',
    projectId: 'excelerate-inquisit',
    storageBucket: 'excelerate-inquisit.firebasestorage.app',
    iosBundleId: 'com.example.excelerateInquisit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbYb8IDwgb51haUGRA2m7n7C0dZLXa7MY',
    appId: '1:50794013537:ios:680bc6df0fd864f62c5b20',
    messagingSenderId: '50794013537',
    projectId: 'excelerate-inquisit',
    storageBucket: 'excelerate-inquisit.firebasestorage.app',
    iosBundleId: 'com.example.excelerateInquisit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeieWqVV-_H9iu_VkTaGMrq3dtdTDLma4',
    appId: '1:50794013537:web:b1bee0df94d2b6922c5b20',
    messagingSenderId: '50794013537',
    projectId: 'excelerate-inquisit',
    authDomain: 'excelerate-inquisit.firebaseapp.com',
    storageBucket: 'excelerate-inquisit.firebasestorage.app',
    measurementId: 'G-CBML42V8LC',
  );

}